version: '3.8'

services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cardinals-portal
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount data files for easy updates
      - ./data.json:/app/data.json:ro
      - ./engineering-law.json:/app/engineering-law.json:ro
    networks:
      - portal-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  portal-network:
    driver: bridge
